/system/app/WallpaperBackup/WallpaperBackup.apk=com.android.wallpaperbackup
/system/app/RKUpdateService/RKUpdateService.apk=android.rockchip.update.service
/system/app/PrintSpooler/PrintSpooler.apk=com.android.printspooler
/system/app/PinyinIME/PinyinIME.apk=com.android.inputmethod.pinyin
/system/app/LiveWallpapersPicker/LiveWallpapersPicker.apk=com.android.wallpaper.livepicker
/system/app/UOTABack/UOTABack.apk=com.uv.droid.uotaback
/system/app/RkApkinstaller/RkApkinstaller.apk=com.android.apkinstaller
/system/app/MboxLauncher/MboxLauncher.apk=com.droidlogic.mboxlauncher
/system/app/WifiDisplay/WifiDisplay.apk=com.rockchip.wfd
/system/app/Chrome/Chrome.apk=com.android.chrome
/system/app/AllApp/AllApp.apk=com.rk_itvui.allapp
/system/app/BasicDreams/BasicDreams.apk=com.android.dreams.basic
/system/app/RkExplorer/RkExplorer.apk=com.android.rockchip
/system/app/RkMusic/RkMusic.apk=com.android.music
/system/app/UOTA/UOTA.apk=com.uv.droid.uota
/system/app/ExactCalculator/ExactCalculator.apk=com.android.calculator2
/system/app/CtsShimPrebuilt/CtsShimPrebuilt.apk=com.android.cts.ctsshim
/system/app/RKDeviceTest/RKDeviceTest.apk=com.rockchip.devicetest


# /system/app/AllApp/AllApp.apk=com.rk_itvui.allapp
# /system/app/BasicDreams/BasicDreams.apk=com.android.dreams.basic
# /system/app/BookmarkProvider/BookmarkProvider.apk=com.android.bookmarkprovider
# /system/app/CaptivePortalLogin/CaptivePortalLogin.apk=com.android.captiveportallogin
# /system/app/CertInstaller/CertInstaller.apk=com.android.certinstaller
# /system/app/Chrome/Chrome.apk=com.android.chrome
# /system/app/CtsShimPrebuilt/CtsShimPrebuilt.apk=com.android.cts.ctsshim
# /system/app/DownloadProviderUi/DownloadProviderUi.apk=com.android.providers.downloads.ui
# /system/app/ExactCalculator/ExactCalculator.apk=com.android.calculator2
# /system/app/FactoryStability/FactoryStability.apk=com.factorytools.factorystability
# /system/app/GmsSampleLayout/GmsSampleLayout.apk=com.google.android.launcher.layouts.gms
# /system/app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk=com.google.android.syncadapters.calendar
# /system/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk=com.google.android.syncadapters.contacts
# /system/app/GoogleExtShared/GoogleExtShared.apk=com.google.android.ext.shared
# /system/app/GooglePrintRecommendationService/GooglePrintRecommendationService.apk=com.google.android.printservice.recommendation
# /system/app/GoogleTTS/GoogleTTS.apk=com.google.android.tts
# /system/app/HTMLViewer/HTMLViewer.apk=com.android.htmlviewer
# /system/app/KeyChain/KeyChain.apk=com.android.keychain
# /system/app/LatinIME/LatinIME.apk=com.android.inputmethod.latin
# /system/app/LiveWallpapersPicker/LiveWallpapersPicker.apk=com.android.wallpaper.livepicker
# /system/app/MboxLauncher/MboxLauncher.apk=com.droidlogic.mboxlauncher
# /system/app/OpaSuwIntegrationSample/OpaSuwIntegrationSample.apk=com.android.opasuwintegrationsample
# /system/app/PacProcessor/PacProcessor.apk=com.android.pacprocessor
# /system/app/PartnerBookmarksProvider/PartnerBookmarksProvider.apk=com.android.providers.partnerbookmarks
# /system/app/PinyinIME/PinyinIME.apk=com.android.inputmethod.pinyin
# /system/app/PrintSpooler/PrintSpooler.apk=com.android.printspooler
# /system/app/RKDeviceTest/RKDeviceTest.apk=com.rockchip.devicetest
# /system/app/RKUpdateService/RKUpdateService.apk=android.rockchip.update.service
# /system/app/RkApkinstaller/RkApkinstaller.apk=com.android.apkinstaller
# /system/app/RkExplorer/RkExplorer.apk=com.android.rockchip
# /system/app/RkMusic/RkMusic.apk=com.android.music
# /system/app/UOTA/UOTA.apk=com.uv.droid.uota
# /system/app/UOTABack/UOTABack.apk=com.uv.droid.uotaback
# /system/app/UserDictionaryProvider/UserDictionaryProvider.apk=com.android.providers.userdictionary
# /system/app/WallpaperBackup/WallpaperBackup.apk=com.android.wallpaperbackup
# /system/app/WebViewGoogle/WebViewGoogle.apk=com.google.android.webview
# /system/app/WifiDisplay/WifiDisplay.apk=com.rockchip.wfd
